version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspace:cached
      - /workspace/vendor
      - /workspace/node_modules
    command: sleep infinity
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=personal_finances
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
    depends_on:
      - postgres
    ports:
      - "8000:80"

  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: personal_finances
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
